version: 2

project_name: iris

before:
  hooks:
    - go mod tidy

builds:
  - id: iris
    main: ./cmd/iris
    binary: iris
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: iris
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE
      - README.md
    ids:
      - iris

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc

release:
  use_existing_draft: true

homebrew_casks:
  - name: iris
    repository:
      owner: sivchari
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/sivchari/iris
    description: "GraphQL REPL client"
    license: MIT
    binaries: [iris]
