package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/sivchari/iris/examples/federation/graph/model"
)

// FindPostByID is the resolver for the findPostByID field.
func (r *entityResolver) FindPostByID(ctx context.Context, id string) (*model.Post, error) {
	for _, post := range r.posts {
		if post.ID == id {
			return &model.Post{
				ID:       post.ID,
				Title:    post.Title,
				Body:     post.Body,
				AuthorID: post.AuthorID,
				Author:   r.findUserByID(post.AuthorID),
			}, nil
		}
	}
	return nil, nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	for _, user := range r.users {
		if user.ID == id {
			return user, nil
		}
	}
	return nil, nil
}

func (r *entityResolver) findUserByID(id string) *model.User {
	for _, user := range r.users {
		if user.ID == id {
			return user
		}
	}
	return nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
