package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/sivchari/iris/examples/federation/graph/model"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	for _, user := range r.users {
		if user.ID == id {
			return user, nil
		}
	}
	return nil, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	posts := make([]*model.Post, len(r.posts))
	for i, post := range r.posts {
		posts[i] = &model.Post{
			ID:       post.ID,
			Title:    post.Title,
			Body:     post.Body,
			AuthorID: post.AuthorID,
			Author:   r.findUserByID(post.AuthorID),
		}
	}
	return posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	for _, post := range r.posts {
		if post.ID == id {
			return &model.Post{
				ID:       post.ID,
				Title:    post.Title,
				Body:     post.Body,
				AuthorID: post.AuthorID,
				Author:   r.findUserByID(post.AuthorID),
			}, nil
		}
	}
	return nil, nil
}

func (r *queryResolver) findUserByID(id string) *model.User {
	for _, user := range r.users {
		if user.ID == id {
			return user
		}
	}
	return nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
