// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Post entity
type Post struct {
	// Post ID
	ID string `json:"id"`
	// Post title
	Title string `json:"title"`
	// Post body content
	Body string `json:"body"`
	// Author user ID
	AuthorID string `json:"authorId"`
	// Author of the post (resolved from User service)
	Author *User `json:"author"`
}

func (Post) IsEntity() {}

type Query struct {
}

// User entity
type User struct {
	// User ID
	ID string `json:"id"`
	// User name
	Name string `json:"name"`
	// User email
	Email string `json:"email"`
}

func (User) IsEntity() {}
